version: '3.9'
services:
  tmux:
    image: ${BASE:-cyd}-common
    working_dir: /app/icmp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app/icmp
    # environment:
    #   - COMPOSE_PROJECT_NAME=icmp
    tty: true
    stdin_open: true
    hostname: tmux
    networks:
      arp:
        ipv4_address: 10.5.0.99
  
  alice:
    image: ${BASE:-cyd}-common
    tty: true
    stdin_open: true
    hostname: alice
    networks:
      arp:
        ipv4_address: 10.5.0.2

  bob:
    image: ${BASE:-cyd}-common
    tty: true
    stdin_open: true
    hostname: bob
    networks:
      arp:
        ipv4_address: 10.5.0.3

  mitm:
    image: ${BASE:-cyd}-kali
    tty: true
    stdin_open: true
    hostname: mitm
    networks:
      arp:
        ipv4_address: 10.5.0.4
  
  flood:
    profiles:
      - attack
    image: ${BASE:-cyd}-kali
    # ICMPv4 Flood Attack 
    #command: hping3 10.5.0.2 -q -n -d 120 -S -p 80 --flood --rand-source
    command: hping3 10.5.0.2 --flood --rand-source --icmp -c 25000
    deploy:
      replicas: 5
    networks:
      arp:

networks:
  arp:
    ipam:
      config:
      - subnet: 10.5.0.0/16
      